package com.example.andrioddock.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF6366F1)
val PrimaryDark = Color(0xFF4F46E5)
val PrimaryLight = Color(0xFF818CF8)
val Secondary = Color(0xFF10B981)
val SecondaryDark = Color(0xFF059669)
val SecondaryLight = Color(0xFF34D399)
val BackgroundLight = Color(0xFFF8FAFC)
val SurfaceLight = Color(0xFFFFFFFF)
val SurfaceVariantLight = Color(0xFFF1F5F9)
val BackgroundDark = Color(0xFF0F172A)
val SurfaceDark = Color(0xFF1E293B)
val SurfaceVariantDark = Color(0xFF334155)
val OnPrimaryLight = Color(0xFFFFFFFF)
val OnSecondaryLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF1E293B)
val OnSurfaceLight = Color(0xFF1E293B)
val OnSurfaceVariantLight = Color(0xFF64748B)
val OnPrimaryDark = Color(0xFFFFFFFF)
val OnSecondaryDark = Color(0xFFFFFFFF)
val OnBackgroundDark = Color(0xFFF8FAFC)
val OnSurfaceDark = Color(0xFFF8FAFC)
val OnSurfaceVariantDark = Color(0xFF94A3B8)
val Error = Color(0xFFEF4444)
val ErrorContainer = Color(0xFFFEE2E2)
val OnErrorContainer = Color(0xFF991B1B)
val OutlineLight = Color(0xFFE2E8F0)
val OutlineDark = Color(0xFF475569)
